apiVersion: v1
kind: Pod
metadata:
  name: redis
spec:
  containers:
  - name: redis
    image: redis
    volumeMounts:
    - name: redis-persistent-storage
      mountPath: /data/redis
  - name: springapp
    image: yanivomc/spring-music:latest
    volumeMounts:
    - name: redis-persistent-storage
      mountPath: /app/data
  volumes:
  - name: redis-persistent-storage
    hostPath:
      path: /data
      type: DirectoryOrCreate