apiVersion: v1
kind: Pod
Metadata:
     name: bear
spec:
  containers:
  - name: animals
    image: supergiantkir/animals:bear
    ports:
    - containerPort: 80

---
apiVersion: v1
kind: Pod
Metadata:
     name: nginx
spec:
  containers:
  - name: animals
    image: nginx:latest
    ports:
    - containerPort: 80